class MainWindow():
    # Main Dimensions
    WIDTH = 1400
    HEIGHT = 800
    X = 200
    Y = 200

    # Calculate Button
    APPEND_BUTTON_WIDTH = 200
    APPEND_BUTTON_HEIGHT = 50
    APPEND_BUTTON_X = int(WIDTH/2) - int(APPEND_BUTTON_WIDTH/2)
    APPEND_BUTTON_Y = HEIGHT - APPEND_BUTTON_HEIGHT
    APPEND_TEXT_SIZE = 14

    # Push Up Button
    PUSH_UP_BUTTON_WIDTH = 200
    PUSH_UP_BUTTON_HEIGHT = 50
    PUSH_UP_BUTTON_X = int(WIDTH/2) - int(APPEND_BUTTON_WIDTH/2) - 20 - PUSH_UP_BUTTON_WIDTH
    PUSH_UP_BUTTON_Y = HEIGHT - PUSH_UP_BUTTON_HEIGHT
    PUSH_UP_BUTTON_TEXT_SIZE = 14
    
    # Push Down Button
    PUSH_DOWN_BUTTON_WIDTH = 200
    PUSH_DOWN_BUTTON_HEIGHT = 50
    PUSH_DOWN_BUTTON_X = int(WIDTH/2) + int(APPEND_BUTTON_WIDTH/2) + 20
    PUSH_DOWN_BUTTON_Y = HEIGHT - PUSH_DOWN_BUTTON_HEIGHT
    PUSH_DOWN_BUTTON_TEXT_SIZE = 14

    # Netlist Line Edit
    NETLIST_LE_WIDTH = 1000
    NETLIST_LE_HEIGHT = 250
    NETLIST_LE_X = int(WIDTH/2) - int(NETLIST_LE_WIDTH/2)
    NETLIST_LE_Y = HEIGHT - APPEND_BUTTON_HEIGHT - NETLIST_LE_HEIGHT
    NETLIST_TEXT_SIZE = 18

    # Netlist Text
    NETLIST_TEXT_WIDTH = 1000
    NETLIST_TEXT_HEIGHT = 400
    NETLIST_TEXT_X = int(WIDTH/2) - int(NETLIST_LE_WIDTH/2)
    NETLIST_TEXT_Y = 10
    NETLIST_TEXT_TEXT_SIZE = 18